name: Dev
on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      tags:
        description: "Manual Workflow"
        required: false
        type: boolean
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.ref_name }}-${{ github.sha }}

jobs:
  build:
    name: Build and Push Multi-Architecture Image
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            maintainer=${{github.repository_owner}}
            org.opencontainers.image.title=${{github.repository}}
            org.opencontainers.image.description=This is ${{github.repository}} build from ${{github.ref_name}}
            org.opencontainers.image.vendor=${{github.repository_owner}}
          tags: |
            type=sha,prefix={{branch}}-
            type=ref,event=branch

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Multi-Architecture Image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: .docker/Dockerfile-build
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
