name: Production Release
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tags:
        description: "Manual Workflow"
        required: false
        type: boolean
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.ref_name }}-${{ github.sha }}

jobs:
  build:
    name: Build and Push Multi-Architecture Image
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            maintainer=${{github.repository_owner}}
            org.opencontainers.image.title=${{github.repository}}
            org.opencontainers.image.description=This is ${{github.repository}} build from ${{github.ref_name}}
            org.opencontainers.image.vendor=${{github.repository_owner}}
          tags: |
            type=ref,event=tag,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=${{ github.ref_name }}-${{ github.sha }},enable=${{ startsWith(github.ref, 'refs/heads/') }}
            type=ref,event=branch,enable=${{ startsWith(github.ref, 'refs/heads/') }}

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set container metadata and create job output
        run: |
          echo '${{ steps.meta.outputs.json }}' > job_output.json

      - name: Upload job output
        uses: actions/upload-artifact@v4
        with:
          name: build_output
          path: job_output.json

      - name: Build and Push Multi-Architecture Image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: .docker/Dockerfile-build
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
